Anfield feature
cohesity/management-sdk-python pull request #47
Opened 2021-06-29 06:06 UTC by naveena-maplelabs

2021-07-13 03:30 UTC, naveena-maplelabs commented
@pyashish Can you please review.

2021-07-15 16:07 UTC, pyashish approved these changes

2021-07-19 15:17 UTC, naveena-maplelabs commented on samples/project-anfield/export_cluster_config.py
> +        api = "nis-providers"
Added Constants

2021-07-19 15:17 UTC, naveena-maplelabs commented
@pyashish Added support for vlans.

2021-07-20 07:00 UTC, pyashish requested changes

2021-07-20 07:00 UTC, pyashish commented on samples/project-anfield/export_cluster_config.py
> +    "vlans": library.get_vlans(cohesity_client),
something doesn't add up: 
1. while exporting you export all these by default 
2. While importing you import selectively. 

What if there is sensitive information and customer doesn't want to export it by default ?

2021-07-20 07:00 UTC, pyashish commented on samples/project-anfield/import_cluster_config.py
> +            if environment not in [env_enum.K_VMWARE]: #env_list:
Make sure this doesn't regress other env type, why did we restrict it to vmware only ?

2021-07-20 07:00 UTC, pyashish commented on samples/project-anfield/import_cluster_config.py
> +            import pdb;pdb.set_trace()
this will stop the code ? Big red flag !

2021-07-22 03:27 UTC, merged